# Generated by Django 2.1.5 on 2019-02-07 03:11

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateTimeField(default=datetime.datetime(2019, 2, 7, 3, 11, 48, 979317, tzinfo=utc))),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('status', models.CharField(choices=[('草稿', '草稿'), ('发布', '发布')], default='草稿', max_length=10)),
            ],
            options={
                'ordering': ('-publish',),
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
