# Generated by Django 2.1.5 on 2019-02-07 07:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190207_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 7, 41, 21, 58743, tzinfo=utc)),
        ),
    ]
