# Generated by Django 2.1.5 on 2019-02-07 09:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20190207_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 9, 27, 43, 814862, tzinfo=utc)),
        ),
    ]
