# Generated by Django 2.1.5 on 2019-02-07 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20190207_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 9, 30, 1, 5758, tzinfo=utc)),
        ),
    ]
