# Generated by Django 2.1.5 on 2019-02-08 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20190207_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 5, 45, 38, 17492, tzinfo=utc)),
        ),
    ]
