# Generated by Django 2.1.5 on 2019-02-08 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20190208_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 8, 45, 34, 803581, tzinfo=utc)),
        ),
    ]
