# Generated by Django 2.1.5 on 2019-02-08 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20190208_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 11, 45, 0, 587335, tzinfo=utc)),
        ),
    ]
